### PR TITLE
beta16

### LINKED ISSUE #17: Not working correctly on beta 13
Seems that this extension is not working corectly on Flarum beta 13. It shows myself as online, but no other members are showing there even if they are definitely online as well.

### LINKED ISSUE #21: Update Beta 14?
Hello Antoine, 
I was wondering if you were going to update this extension for Beta 14 ( Really liked the "money" ext as well that got released for Beta 14 :) )
Thanks!

### LINKED ISSUE #25: Update Beta 16?
Hello, will the extension be updated to beta 16?

### PR DESCRIPTION
**Pull request by Nearata**
fixes #25 
fixes #21 
fixes #17

### CODE REVIEW

**Comment by Nearata** [comment]
I made this a draft because i need answers

- the `and {more} more...` is no longer used. Do you want to keep this feature? Idk actually how to fix this, now that is all handled in backend. the only way that i see, is to send, even if limited by admin setting, all the online users. but i don't like this.
- i'd like to get rid of all extra translations.
- while testing the extension, i see that the list of online users is in a problematic position. perhaps a style more like [Discourse](https://camo.githubusercontent.com/652e5c280cca20c9840186237ebfb31d16735a25d2e8db8df3ad73e9c46a3f75/68747470733a2f2f643131613674726b676d756d73622e636c6f756466726f6e742e6e65742f6f726967696e616c2f33582f612f662f616639313836636637623662363934613865303030313866633637626365376639663465333636302e676966) might be better.
- i saw that in frontend you sorted the list of users in order of time, i removed it. is there a reason for it? do you want to keep this behavior?

File: .editorconfig [hunk 1]
```diff
@@ -0,0 +1,16 @@
+root = true
```
Comment (AntoineFr) [inline .editorconfig]: I'd like to not include this file

File: .gitattributes [hunk 2]
```diff
@@ -0,0 +1,7 @@
+# Auto detect text files and perform LF normalization
```
Comment (AntoineFr) [inline .gitattributes]: I'd like to not include this file

File: src/LoadOnline.php [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+        $actor = $request->getAttribute('actor');
+        $ago = Carbon::now()->subtract(5, 'minutes');
+
+        $online = User::query()->whereRaw('? < last_seen_at', [$ago])->get();
+
+        $filtered = collect($online)->map(function ($user) use ($actor) {
+            if ($user->getPreference('discloseOnline') || $actor->can('viewLastSeenAt', $user)) {
+                return $user;
+            }
+        });
```
Comment (AntoineFr) [inline src/LoadOnline.php]: I would suggest the following code because in my tests I had a `null` in the resulting array if the user chose to hide his online status.
```php
        $filtered = collect($online)->filter(function ($user) use ($actor) {
            return ($user->getPreference('discloseOnline') || $actor->can('viewLastSeenAt', $user));
        });
```

File: src/LoadOnline.php [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+
+        $max = (int) $this->settings->get('antoinefr-online.displaymax', 5);
+
+        $data['online'] = $filtered->slice(0, $max <= 0 ? null : $max);
```
Comment (AntoineFr) [inline src/LoadOnline.php]: I found a `take` method which could be used here

```php
        $data['online'] = $filtered->take($max);
```

File: src/LoadOnline.php (hunk 3 above)
Comment (Nearata) [reply src/LoadOnline.php]: Yeah right, i forget to [reject](https://laravel.com/docs/8.x/collections#method-reject) empty user.

**Comment by AntoineFr** [comment]
First, thank you for your work!

And here are some answers to your questions :

>     * the `and {more} more...` is no longer used. Do you want to keep this feature? Idk actually how to fix this, now that is all handled in backend. the only way that i see, is to send, even if limited by admin setting, all the online users. but i don't like this.

I'd like to keep this feature, maybe we can add a new attribute in `ShowForumController` like `onlineMore` which holds the count of remaining online users.

>     * i'd like to get rid of all extra translations.

Why not, maybe we can submit a pull request to the corresponding languages packs to keep the translation that was made.

>     * while testing the extension, i see that the list of online users is in a problematic position. perhaps a style more like [Discourse](https://camo.githubusercontent.com/652e5c280cca20c9840186237ebfb31d16735a25d2e8db8df3ad73e9c46a3f75/68747470733a2f2f643131613674726b676d756d73622e636c6f756466726f6e742e6e65742f6f726967696e616c2f33582f612f662f616639313836636637623662363934613865303030313866633637626365376639663465333636302e676966) might be better.

I think we could reconsider this question in a separate PR after updating to beta16, maybe add a setting to override the position.

>     * i saw that in frontend you sorted the list of users in order of time, i removed it. is there a reason for it? do you want to keep this behavior?

The idea was to display on top of the list the most recent online users, I preferred it that way.

File: src/LoadOnline.php (hunk 4 above)
Comment (Nearata) [reply src/LoadOnline.php]: the reason i didn't used this is because if a user save the settings without input something, 0 is returned instead of 5. It looks like 5 is returned only if (the setting) is null or undefined. or maybe you want this behavior?

Comment (AntoineFr) [reply src/LoadOnline.php]: I think something like this would be nice: 

- max = -1 (or maybe < 0) -> display all online users
- max = 0 -> display no online user (could be used with `{more}` to only display `and XXX user(s)` without showing the usernames of online users)
- max > 0 -> display `max` users

What do you think?

Comment (Nearata) [reply src/LoadOnline.php]: The second one you mean like `There are {more} users online` or `{more} users are online` ?

Comment (AntoineFr) [reply src/LoadOnline.php]: Yes, something like that. It is related to the first point you highlighted in this message: https://github.com/AntoineFr/flarum-ext-online/pull/26#issuecomment-835531948

> the `and {more} more...` is no longer used.

If `$max` is 2, we would have:
```
# Who is online?
(avatar) username
(avatar) username
and 5 more...
```

If `$max` is 0, we would have:
```
# Who is online?
and 7 more...
```

Of course it would need a text that works in both versions, or an `if` statement.

File: src/LoadOnline.php [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+    protected $settings;
+
+    public function __construct(SettingsRepositoryInterface $settings)
+    {
+        $this->settings = $settings;
+    }
+
+    public function __invoke(ShowForumController $controller, &$data, ServerRequestInterface $request, Document $document)
+    {
+        /** @var User */
```
Comment (AntoineFr) [inline src/LoadOnline.php]: Is this line needed?

**Review by AntoineFr — APPROVED** [review]

File: src/LoadOnline.php (hunk 5 above)
Comment (Nearata) [reply src/LoadOnline.php]: i needed linting in that moment and forgot to remove it xD

**Comment by AntoineFr** [comment]
Thank you for your pull request!

Do you have the same username on GitHub and discuss.flarum.org to give you credit?

**Comment by Nearata** [comment]
> Thank you for your pull request!

Thank you for the collaboration!

> Do you have the same username on GitHub and discuss.flarum.org?

yes
